### ISSUE TITLE
when you turn the client's monitor to sleep and it turns back on, the turn on on startup doesn't work and they need to reopen the application

### ISSUE THREAD

**Issue by Rixxless** [MaxXor/xRAT#1219] opened 2023-10-29 08:06 UTC
### Quasar version

1.4.0

### Server installed .NET version

.NET 6.0

### Server operating system

Windows 11/Server 2022

### Client installed .NET version

.NET 6.0

### Client operating system

Windows 11/Server 2022

### Build configuration

Release

### Describe the bug

when you turn the client's monitor to sleep and it turns back on, the turn on on startup doesn't work and they need to reopen the application

### How to reproduce

connect, turn client's pc to sleep, when the person turns it back on it doesn't make a new connection

### Expected behavior

It should reestablish the connection

### Actual behavior

??

**Comment by MaxXor** [comment] 2023-10-30 17:42
Duplicate of https://github.com/quasar/Quasar/issues/744.

It's best to disable sleep mode of the computer at the moment until a proper fix is implemented.

**Closed as completed by MaxXor** 2023-10-30 17:42 UTC
Labels: duplicate
