### ISSUE TITLE
Form listviewitem null reference

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#231] opened 2015-05-27 18:47 UTC
I have no clue why this is happening, but i installed 50 clients on a VM, and tried updating them all at once.  The first time my server crashed and stopped responding.  I tried debugging it but it wasn't throwing any exceptions when debugging.  The only lead I have is from trying to disconnect an item that is still in the listview and it is claiming "object reference not set to an instance of an object."

any ideas?

**Comment by MaxXor** [comment] 2015-05-27 18:51
Hm, tested it on Windows 7 and working fine. What settings did you use for the 50 clients? And what for the update?

**Comment by d3agle** [comment] 2015-05-27 18:54
Normal settings, no installation, different mutex for each, keylogger disabled.

Selected all 50, update from file, server stopped responding after it got down to ~25
The second time, it went down to ~15 clients.  This time, the clients were still in the listview and the server did not crash, however when trying to execute a command on the client I would get a null reference exception dialog claiming the object had already been disposed

**Comment by d3agle** [comment] 2015-05-27 18:58
Just got an exception in debugger

![](http://puu.sh/i2J0C/e42fef49c6.png)

**Comment by MaxXor** [comment] 2015-05-27 19:03
What's null, the `ListViewitem`, the `Tag` or `client`??

**Comment by d3agle** [comment] 2015-05-27 19:03
@MaxXor, ListViewItem

**Comment by d3agle** [comment] 2015-05-27 19:05
Would placing a lock be appropriate in a case like this?  I think it's caused by clients disconnecting asynchronously while the delegate method has a reference to a listviewitem that is no longer created

**Comment by MaxXor** [comment] 2015-05-27 19:06
Can you check if it's working with a `lock`? Could be the reason.

**Comment by d3agle** [comment] 2015-05-27 19:06
Sure, will try now

**Comment by d3agle** [comment] 2015-05-27 19:07
I'm sorry, I've no idea where to place the lock or what object to lock.

**Comment by d3agle** [comment] 2015-05-27 19:09
I'm assuming lstClients would be the object to lock!

**Comment by MaxXor** [comment] 2015-05-27 19:13
place the `lock (lstClients)` right before the foreach-loop.

**Comment by d3agle** [comment] 2015-05-27 19:14
Hmmm nope, still happening :(

Placed a lock on lstClients around the loop and still getting null reference

**Comment by MaxXor** [comment] 2015-05-27 19:19
I can't reproduce this still, do you use Upload Update or Update via Download from website?

**Comment by d3agle** [comment] 2015-05-27 19:20
Update from file, I'm looking there now in the code and wondering if the threading has something to do with it.

**Comment by MaxXor** [comment] 2015-05-27 19:20
The thread is just there so the upload process doesn't freeze the form, this shouldn't be the problem..

I can't reproduce this with 40 test clients. :(

**Comment by d3agle** [comment] 2015-05-27 19:25
Hmmmm, well it doesn't happen every time, it's happened 3 times out of 6 tests.  It is really weird that the listviewitem is nulled... I will keep trying to see what might be happening

**Comment by d3agle** [comment] 2015-05-27 19:29
One thing that I've noticed, is after highlighting the all of the ListViewItems and updating, some of the listview items de-select (aren't highlighted) when the clients start to update and disconnect

**Comment by MaxXor** [comment] 2015-05-27 19:30
@d3agle that's no problem as the selected clients will be copied into a list. :)
https://github.com/MaxXor/xRAT/blob/master/Server/Forms/FrmMain.cs#L358

**Comment by d3agle** [comment] 2015-05-27 19:32
I noticed that :) I'm stepping through to see what might be happening lower into it the code

**Comment by d3agle** [comment] 2015-05-27 19:38
What about using LINQ to select the client from the list view with the specified tag?

**Comment by yankejustin** [comment] 2015-05-27 19:50
@MaxXor @d3agle Placing a lock on <code>lstClients</code> is useless. The lock is violated whenever <code>lstClients</code> changes. Consider creating a <code>const</code> or <code>readonly</code> object for locking. Ensure the object used to lock <i>will not change</i>.

**Comment by yankejustin** [comment] 2015-05-27 19:53
I am actually going to re-do this quite a bit (similar to the RemoteShell changes I just made). Though invoking on the form works, we really need to separate the logic that should be kept in the form (GUI-modifying) with the things that <i>really</i> should be kept separated entirely.

**Comment by d3agle** [comment] 2015-05-27 19:53
I will try that.  Just wanted to point this out, not sure if its placebo or perhaps the cause, but I get the null reference exception when I use my middle mouse wheel to scroll through the list while the clients are disconnecting/updating.  Scrolling through the list (with mouse wheel) while the clients are selected I notice that one of them/some of them de-select.  When I update them all, and quickly un-select them all, I don't get any reference thrown.  If I leave them all selected and don't scroll through the list, I get no exception.

**Comment by yankejustin** [comment] 2015-05-27 19:56
To also answer your question above, <i>yes</i>, this is a threading issue. :)

**Comment by d3agle** [comment] 2015-05-27 21:21
After removing this line: https://github.com/MaxXor/xRAT/blob/master/Server/Forms/FrmMain.cs#L193

I no longer have this issue.  Is this event used for anything in particular?

**Comment by MaxXor** [comment] 2015-05-28 09:02
Would you mind checking the issue after the latest commit?

**Comment by d3agle** [comment] 2015-05-28 10:33
It it still happening.  I do believe this is a threading issue, due to the inconsistency of being able to reproduce this bug.  It happens quite a bit when I highlight 50 clients -> update from file -> de-select them all, and then select some of them as they are disconnecting.

**Comment by d3agle** [comment] 2015-05-28 11:52
Another strange thing I've noticed that is probably related to this is when I disconnected 100 clients at once, this was the result.  Notice the text is drawn differently in one listviewitem

![](http://i.gyazo.com/17253c47cd01e1017b8e8135a4e618b4.png)

**Comment by MaxXor** [comment] 2015-05-28 20:03
Working on a fix for this.

**Closed** 2015-05-28 22:25 UTC
Labels: bug

**Comment by d3agle** [comment] 2015-05-29 12:08
Unfortunately, the problem persists :( The behavior is worse after the update.

**Comment by MaxXor** [comment] 2015-05-29 13:34
@d3agle Why?

**Comment by d3agle** [comment] 2015-05-29 13:49
This is what it is like closing the server: http://i.gyazo.com/63622aefcab03cfeb09e9b43e451097d.mp4

http://gyazo.com/abfa94f451e178aa046d5c42ee1a31e6.mp4
"Cross-thread operation not valid: Control 'lstClients' accessed from a thread other than the thread it was created on."

The problem I was referring to is the behavior when updating/disconnecting clients.  sometimes the listviewitem will stay in the listview even though the client is disconnected

**Comment by MaxXor** [comment] 2015-05-29 13:50
The closing server behaviour was the same before, lol. Well, yea I'm still working on a final fix for this disconnection bug.

**Comment by d3agle** [comment] 2015-05-29 13:52
Oh ok, I hadn't really tested closing the server prior to this update.  I'm stumped on why this is happening, but I hope you can fix it!  It's so annoying lol

**Comment by MaxXor** [comment] 2015-05-29 13:53
Yes, sure. The server just tries to make a clean disconnect from the client. x)

**Comment by yankejustin** [comment] 2015-05-29 16:39
@d3agle Please try it out now. As I have said before, locking on <code>_clients</code> is actually useless in a spot that messes with the object.
<br />
<h2>Example:</h2>
1. Acquire a lock on <code>_clients</code>.
2. Disconnecting user, so remove entry 0 from <code>_clients</code>.
3. Another thread tries to enter. The previous entering thread acquired a lock on <code>_clients</code>, but <code>_clients</code> <i>has been changed</i>, so it may enter (when it shouldn't be able to).
<hr />
With that example, that is why I lock on objects that I know don't change, and why it is important to prevent changes to them.

**Comment by d3agle** [comment] 2015-05-29 16:58
I tried your branch and I think we are closer to the culprit.

I installed 100 clients, and tried reconnecting them all at once.  5 of them stayed in the listview and I was given an exception here: System.NullReferenceException: Object reference not set to an instance of an object at 'xServer.Core.Misc.ListViewColumnSorter.Compare(Object x, Object y) at line 51.

**Comment by yankejustin** [comment] 2015-05-29 17:03
I forgot to implement a lock for <code>GetSelectedClients</code>. Couldn't sort correctly because of multiple access to <code>lstClients</code>. x)
Try again. :)
If needed, add to <b><a href="https://github.com/MaxXor/xRAT/pull/239">my pull request</a></b>.

**Comment by d3agle** [comment] 2015-05-29 17:06
Got deadlock somewhere :O

**Comment by d3agle** [comment] 2015-05-29 17:15
Strangely enough, this happens when 6 clients are selected.  When 5 clients are selected, it will leave one unhighlighted.  Anything <= 4 will function fine :|

**Comment by yankejustin** [comment] 2015-05-29 20:55
@d3agle Please try it again and see if this is better.

**Comment by d3agle** [comment] 2015-05-29 21:06
@yankejustin, My previous comments were towards the most recent commit, https://github.com/yankejustin/xRAT/commit/cdfe93f69a6fa89da522a40717040c44117d0d60

Prior to locking in the GetSelectedClients method it worked fine (didn't get deadlock after sending commands to less than 4 clients, 5 had weird behavior, 6 or more would cause a deadlock)

**Comment by yankejustin** [comment] 2015-05-29 21:09
@d3agle Right, I forgot to clarify that I just changed it 16 minutes ago. Try withthe newest change and see if it still deadlocks.

**Comment by yankejustin** [comment] 2015-05-29 21:10
If it still does not work then I think I have a strong idea what will. :)

**Comment by d3agle** [comment] 2015-05-29 21:10
I don't see any changes from the last commit :X

**Comment by yankejustin** [comment] 2015-05-29 21:14
@d3agle Sorry, forgot to press <i>sync</i>! x)

**Comment by d3agle** [comment] 2015-05-29 21:14
:D no problem, testing now

**Comment by yankejustin** [comment] 2015-05-29 21:15
Mind if I ask your exact methods of testing?

**Comment by d3agle** [comment] 2015-05-29 21:20
Well, since I was too lazy to generate random mutex in the code for the builder, I spend about 5 minutes creating 100 clients name 1.exe - 100.exe.  Put them in a folder -> Copied to VM -> executed them all.  Then I test them without debugger first, to see what runtime errors might occur trying various different things (Mainly habitual things).  Then if any errors occur, I test the same situations with debugger to see what line of code is breaking.

**Comment by d3agle** [comment] 2015-05-29 21:21
Mainly looking for behavior consistency/inconsistency

**Comment by yankejustin** [comment] 2015-05-29 21:22
Ew... I see a cross-thread exception in <code>GetSelectedClients()</code> that is in the <code>MaxXor/master</code> branch. I am going to fix that very quick.

**Comment by d3agle** [comment] 2015-05-29 21:22
Ok, the deadlock is still occuring, however it doesn't happen as often.  It appears to happen when about ~60 clients have disconnected

**Comment by yankejustin** [comment] 2015-05-29 21:25
What are you doing before it locks?

**Comment by d3agle** [comment] 2015-05-29 21:25
I'm selecting all the clients, and sending reconnect/disconnect commands.  It's locking at random times

**Comment by d3agle** [comment] 2015-05-29 21:25
I don't touch anything after I send the commands

**Comment by MaxXor** [comment] 2015-05-29 21:27
I have a fix ready, please don't work on this now. :)

**Comment by d3agle** [comment] 2015-05-29 21:29
Sounds good :+1:

**Comment by yankejustin** [comment] 2015-05-29 21:30
Oh, okay...

**Comment by yankejustin** [comment] 2015-05-29 21:31
That is funny because I just fixed the eventhandlers and I believe the rest, @d3agle xD

**Comment by MaxXor** [comment] 2015-05-29 21:36
I made a lot more changes.

**Comment by yankejustin** [comment] 2015-05-29 21:38
Looks delicious. Nice work. :)

**Comment by MaxXor** [comment] 2015-05-29 21:39
Thanks, I this should also fix other cross-threading problems which may occur too.

**Comment by d3agle** [comment] 2015-05-29 22:21
I cannot break it.  Good stuff.

http://i.gyazo.com/e1e73e57e3a30b78d5f82d5287832d1b.mp4

**Comment by yankejustin** [comment] 2015-05-29 22:27
Gorgeous. :)
I do eventually want to use a bit of <code>SuspendLayout()</code> and <code>ResumeLayout()</code> so it doesn't flicker so much like that.

**Comment by d3agle** [comment] 2015-05-29 22:32
@yankejustin, take a look at this as well http://www.virtualdub.org/blog/pivot/entry.php?id=273

Perhaps this could be useful :D

**Comment by yankejustin** [comment] 2015-05-29 22:35
LOL... "ListViewWithLessSuck"
That made my day. :)
<hr />
Eventually I do want to give some of the controls some love where it is needed, but that could be a bit of a pain.

**Comment by d3agle** [comment] 2015-05-29 22:43
That's true :( but it would definitely be an appealing touch.  I haven't looked into theming extensively, but it might be a fun little side-project.  It would be really cool if we had features to have different themes/color schemes.  But the flickering is pretty annoying, just looks unclean lol.

**Comment by yankejustin** [comment] 2015-05-29 22:47
Yes, I agree. It is something I feel is important for the next version. I want to make it look much better, but that will certainly take some effort.

**Comment by MaxXor** [comment] 2015-05-30 06:11
Just add your new Listview code to this file: https://github.com/MaxXor/xRAT/blob/master/Server/Controls/ListViewEx.cs

And see if the flickering is gone. :D

**Comment by yankejustin** [comment] 2015-05-30 06:58
:+1:  :hankey:  :+1:

**Comment by d3agle** [comment] 2015-05-31 19:23
Is this what you guys mean by flicker?  I'm still noticing some weird behavior
http://i.gyazo.com/6fed8b019d8d2f20c9e639206a67aff6.mp4

**Comment by MaxXor** [comment] 2015-05-31 19:26
This is the GUI (listview in this case) which updates when each client gets removed from the list, not the real flickering like it was before.
