### ISSUE TITLE
Remote chat implementation with client request.

### ISSUE THREAD

**Issue by Knakiri** [MaxXor/xRAT#1231] opened 2023-12-26 23:12 UTC
### Problem description

There has been communication issues when i am using this tool i need to talk with the client in order to understand each other

### Proposal

before we run remote chat in the server client gets notification to accept or decline offer to chat with the server.
also in the remote chat sending files would be cool too

**Comment by MaxXor** [comment] 2023-12-27 12:08
Duplicate of https://github.com/quasar/Quasar/issues/351

**Closed as completed by MaxXor** 2023-12-27 12:08 UTC
Labels: duplicate
