### ISSUE TITLE
Remote Desktop Bug

### ISSUE THREAD

**Issue by d3agle** [MaxXor/xRAT#298] opened 2015-07-27 11:52 UTC
I believe this is why the InvalidOperationExceptions are thrown.  The `UnsafeStreamCodec` is trying to use the image at the same time the `FrmRemoteDesktop` is accessing the image.

This post explains the best solution of restricting access to the object to one thread
http://stackoverflow.com/a/1852451

Also, the Remote Desktop can get really laggy when it is maximized, or if the remote client's resolution is larger than the picturebox.  Could the issue be caused by the `SendBlocking` method? of `GetDesktop` packets?

**Comment by d3agle** [comment] 2015-07-27 14:32
This bug (where the GDI gets screwy and draws the red X and crashes and throws exception) appears to only happen when using Remote Desktop with Windows 10 (Pro Insider Preview Eval copy Build 10074).

The lag and delays occur on any machine when the form is maximized, however.

**Comment by d3agle** [comment] 2015-07-27 14:38
Another thing I've noticed, is that if the resolution of the Client machine is smaller than the form of the Remote Desktop, this is when the lag happens most.  This may be why maximizing the Remote Desktop form on the Server will have lag/delays when the form is larger than the resolution of the Client machine.

**Comment by d3agle** [comment] 2015-07-27 17:33
@MaxXor, Could the issue be for laggy/delayed performance be due to the `SendBlocking` method?

Also, Remote Desktop worked on Windows 10 prior to the latest update

**Comment by d3agle** [comment] 2015-07-27 18:35
Also, I believe this is why we are getting all of the InvalidOperationExceptions
http://stackoverflow.com/a/1852451

**Comment by MaxXor** [comment] 2015-07-27 19:44
Oh yea, the first bug is not nice.. I think the problem is the server which receives the new screen images too fast, I tried adding some locks to it, but seems it didn't change anything.

I'll look into this further.

**Comment by yankejustin** [comment] 2015-07-27 21:20
@MaxXor That is actually incorrect. Using <code>Clone()</code> on a <code>Bitmap</code> <i>does</i> provide you with a new <code>Bitmap</code> object with its own copied values. However, <b>pixel data is shared with the original object</b>.

**Comment by yankejustin** [comment] 2015-07-27 21:27
Also, we should dispose of <code>picDesktop's</code> <code>Image</code>. Calling <code>Dispose()</code> on <a href="https://github.com/MaxXor/xRAT/blob/358324c7c26b1feb92731f86609e6996183b8823/Server/Forms/FrmRemoteDesktop.cs#L97">this object</a> isn't going to really help us much because we are actually not disposing of <code>picDesktop's</code> <code>Image</code>.
To end the long wall of text, I would also like to point out that we should add <code>picDesktop.SuspendLayout()</code> before changing the image, and <code>picDesktop.ResumeLayout()</code> after changing the image. This should remove the flicker effect.

**Comment by MaxXor** [comment] 2015-07-27 21:44
@yankejustin Thanks, didn't know about this. I think the code should now create a deep copy of the bitmap. I think it does dispose the old bitmap from the picturebox correctely, because we are just changing the picturebox image, but didn't take care of the old image before, so we need to wait till the GC collects it.

**Comment by yankejustin** [comment] 2015-07-27 21:54
@MaxXor There is actually another issue I noticed. There is quite a significant amount of lag that aggregates. It builds up (got it to ~25 seconds of lag in under 2 minutes) and causes the user to be unable to pause the changing of <code>picDesktop.Image</code>.

**Comment by MaxXor** [comment] 2015-07-27 22:03
@yankejustin Do you also have Remote Desktop window maximized?

**Comment by yankejustin** [comment] 2015-07-27 22:05
I had it maximized at some point, but it will lag for me regardless. It seems as if the Client still continues to send the changed image and the Server will continuously handle it... Even if I press the Stop button.

**Comment by MaxXor** [comment] 2015-07-27 22:11
@yankejustin Can you check if the lag gets worse when you just keep it at the same size?

**Comment by yankejustin** [comment] 2015-07-27 22:13
@MaxXor It seems that increased movement on the Client (more changing pixels) results in increasing lag.

**Comment by MaxXor** [comment] 2015-07-27 22:18
I'm working on a fix for this.

**Comment by d3agle** [comment] 2015-07-27 22:34
@MaxXor, while you are working on this, could you also add this to the `ScreenHelper` class?  It makes transparent areas visible, so you are able to interact and see more of the desktop when it draws the image http://puu.sh/jfgRh/3458ae66a6.png

Also, I'm 100 percent sure its because the object is being accessed at the same time, because I'm getting an error that says that.  This happens in multiple scenarios.  Recreating these scenarios can be tough because you have to get lucky you time them right.  Try dragging the border of the remote desktop form so that the width of the form is expanding.  Eventually it will throw an exception stating that the object is in use somewhere else.  There are three methods that calculate the size of the image to display in the picturebox and this accesses the image that is being invoked rapidly, and also the image that is being decoded in the `UnsafeStreamCodec` class

Hope you fix it! :D

**Comment by d3agle** [comment] 2015-07-27 22:40
Also, before I scurry off for sleep xD, The lag I was experiencing would also happen if the Remote Desktop form was smaller than the resolution of the client machine.  This was also causing lag but it might have just been placebo.  I would like to think its because the `GetDesktop` responce packet is being sent to the server by `SendBlocking` method.  Not 100 percent on that but I hope you guys can figure it out!

**Comment by yankejustin** [comment] 2015-07-27 23:00
@d3agle Thank you for the input!
And yes, the pixel data is <b>very</b> likely being accessed in different places and manipulated. This is because (as I stated above) the <code>Clone()</code> method of a <code>Bitmap</code> actually will still share pixel data with the original.

**Comment by yankejustin** [comment] 2015-07-27 23:38
@d3agle Read your other comment a second time and realized the new(ish) <code>SendBlocking</code> method. Why do we send these packets in a blocking fashion? Why can't it be in a way similar to UDP packets and just send the data? This makes sure that we are using the latest packets from the Client.

**Comment by d3agle** [comment] 2015-07-28 05:29
@yankejustin, Thank you for the explanation.  I see how that would make a world of difference in responsiveness.

Here is an example of the lag.  I hope that this link will help provide some insight on to why this might be happening.  http://i.gyazo.com/b8abcefab48a2acdc2042701045e327e.mp4

The Client machine has a resolution of 800x600.  Notice when I move the forms width a smidge, the lag shortly ensues :disappointed:

**Comment by d3agle** [comment] 2015-07-28 06:32
@MaxXor, the deep copying of the Bitmap object seems to be working for me.  I've been trying to break it for the past hour and haven't been successful.

**Comment by d3agle** [comment] 2015-07-28 07:30
I believe this post is relevant to the "lag" we are experiencing.
http://stackoverflow.com/a/14282467

**Comment by MaxXor** [comment] 2015-07-28 09:30
@d3agle `CAPTUREBLT` causes my mouse cursor on Windows 7 to disappear when `BitBlt` is called. Yes, only the Server is affected. I've tried now resizing the image before updating the picturebox, but when the window is maximzed the lag still occurs. :worried:

@yankejustin The `SendBlocking` is important (also for File transfers) because the bytes of the next image shouldn't get allocated until first one is sent. Without this, it would pump the memory with the images.

**Comment by d3agle** [comment] 2015-07-28 09:49
@MaxXor, I see what you mean my mouse is flickering.  I wonder if there are any other ways to do something similar.. without it, working on machines (Windows 10 for example) might be difficult :(

Also, perhaps we could try using a control other than the PictureBox to draw the image?

**Comment by d3agle** [comment] 2015-07-28 09:55
It is quite a bit slower after (without resizing form) #298

**Comment by MaxXor** [comment] 2015-07-28 11:58
@d3agle In R4 the Remote Desktop was actually slow, the server did always send a `DesktopReceived` and then the client answered with the next image, like a ping pong.

**Comment by d3agle** [comment] 2015-07-28 12:03
@MaxXor, That is true. But now, the server is being bombarded with packets, and the terrible picturebox optimizations limit us :(  

Do you think it would be viable to create our own control so we have more control of the way the OnPaint event processes images?

**Comment by MaxXor** [comment] 2015-07-28 12:05
@d3agle I guess yes, we'll need to change how the image gets drawn to the form.

https://stackoverflow.com/questions/11030706/c-sharp-fast-pixel-rendering

**Comment by yankejustin** [comment] 2015-07-28 17:07
I'm working on this.

**Comment by yankejustin** [comment] 2015-07-28 22:31
@MaxXor Why don't we flush the queue of <code>Bitmaps</code> after the Stop Button is pressed? When it is not cleared, we get the stream of residual pictures that is likely undesirable. Perhaps it should be an option to queue the images together, or to flush the queue on stopping of image updating.

**Comment by d3agle** [comment] 2015-07-29 01:44
Here is a great article showing how to process the scaled images in the OnPaint() event:
http://www2.sys-con.com/itsg/virtualcd/dotnet/archives/0101/brown/index.html

The example code is towards the bottom of the page

**Comment by d3agle** [comment] 2015-07-29 01:49
But if all else fails, SharpDX looks like a nice library

**Comment by MaxXor** [comment] 2015-07-29 07:37
@yankejustin I think it's only needed to clear the queue when the form closes.

**Comment by MaxXor** [comment] 2015-07-29 08:42
I've created a new branch called `remote-desktop`, thats the old Remote Desktop with some improvements from the new one. You can check it out and see the FPS is a lot lower. But I also don't want to add SharpDX or any other DirectX wrapper.

**Comment by d3agle** [comment] 2015-07-29 10:05
I think we should use the old system too.  I just installed Windows 10 on my host and I'm getting a steady 27 fps streaming from my second monitor (At 75% quality).

**Comment by MaxXor** [comment] 2015-07-29 19:31
@d3agle I think that's a good solution, gonna merge the changes now.

**Closed** 2015-07-29 19:31 UTC
Labels: bug
