### ISSUE TITLE
Keylogger Escape key

### ISSUE THREAD

**Issue by OpenSourceCS** [MaxXor/xRAT#95] opened 2015-05-07 11:09 UTC
Add Escape key since many use Ctrl + Escape key to open start screen (or menu), Task Manager in windows by using Ctrl+Shift+Esc command. So somebody add [ESC] key.

**Comment by yankejustin** [comment] 2015-05-07 12:29
Please test my code to see if it functions as intended.

**Comment by yankejustin** [comment] 2015-05-07 13:38
@MaxXor If possible, please assign this to me.

**Comment by MaxXor** [comment] 2015-05-07 16:11
I can only assign issues to people who are collaborators (push access to this repository) of this repository.

See: https://stackoverflow.com/questions/8888675/in-github-issue-tracker-can-non-admin-users-assign-users-and-labels#8890803

**Comment by yankejustin** [comment] 2015-05-07 16:14
Oh. I see. Thank you.

**Comment by MaxXor** [comment] 2015-05-07 16:15
@yankejustin I know you are working on this. :) Send the pull request when you think the problems are solved.

**Comment by yankejustin** [comment] 2015-05-12 17:14
@MaxXor This can actually be closed now since these keys work. While we are testing combinations and such, it is still not perfect. However, the escape key is supported in the branch. :)

**Closed** 2015-05-19 16:22 UTC
Labels: enhancement
