### ISSUE TITLE
Release Candidate for RELEASE4

### ISSUE THREAD

**Issue by MaxXor** [MaxXor/xRAT#209] opened 2015-05-26 17:49 UTC
Please download the artifcats from the latest [AppVeyor](https://ci.appveyor.com/project/MaxXor/xrat) builds in Release mode and help testing all features for the next RELEASE4. Please report all bugs you find.

I think the current status of the `master`-branch is stable, some minor bugs only I hope.

**Comment by d3agle** [comment] 2015-05-26 18:04
Other than the little bugs that were recently fixed, Reverse Proxy in context menu has no icon! XD 

I'll continue to try and break things, but everything seems stable!

**Comment by MaxXor** [comment] 2015-05-26 18:04
Gonna add one. :D

**Comment by yankejustin** [comment] 2015-05-26 23:32
We need to also test these features for multiple clients. I doubt most of us are testing many of these features using more than one client.

**Comment by yankejustin** [comment] 2015-05-26 23:49
@MaxXor :)

<h1>Remote Shell issue</h1>
<h4>Problem:</h4>
Server tells client to execute commands with the word "exit" in certain ways that are not ordinary, causing behavior that is not very desirable.
<h4>Reproduction of the issue:</h4>
<b>Examples of offending text:</b>
1. <code>exit exit</code>
3. <code>start exit exit</code>

**Comment by rabbitsmith** [comment] 2015-05-27 10:19
afaik xrat is stable but in win10 the remote desktop does not start sometimes when start button is clicked. (at least for me). probability of not starting is 20 of 100 . and file manager download isnt sorking for me

**Comment by rabbitsmith** [comment] 2015-05-27 10:20
afaik xrat is stable but in win10 the remote desktop does not start sometimes when start button is clicked. (at least for me). probability of not starting is 20 of 100 . and file manager download isnt working for me

**Comment by d3agle** [comment] 2015-05-27 10:27
@rabbitsmith, i'll be doing some testing with win10.  What is your build of win10 is you don't mind me asking?

**Comment by rabbitsmith** [comment] 2015-05-27 10:36
9879 64bit

**Comment by d3agle** [comment] 2015-05-27 10:42
@rabbitsmith, Thank you.  I'm using the Windows 10 Pro Insider Preview (Build 10074 32bit) and everything seems to be working fine for me.  If I recall correctly, you had mentioned your uplink was slow.  Perhaps this could be a factor?

**Comment by d3agle** [comment] 2015-05-27 10:46
Do you have any other OS's you could test this on?

**Comment by rabbitsmith** [comment] 2015-05-27 10:57
my isp bans uploading of files. i have a data plan only on my phone. i test xrat only on lan with two pcs running win10 9879

**Comment by rabbitsmith** [comment] 2015-05-27 11:01
the file manager transfer is really fast but on my pc the integrity of files isnt assured. i transferred a 7mb file with no errors and hashes matching. the problem still persists for files larger than 15 mb.

i mentioned my uplink was slow because i couldnt upload the xrat binaries and the screenshot.

**Comment by d3agle** [comment] 2015-05-27 11:08
Thank you for the information.  I will try and emulate this problem you are having.

**Comment by yankejustin** [comment] 2015-05-27 16:07
@MaxXor I apologize if this is a foolish question, but would it be possible to add me as a contributor?

**Comment by MaxXor** [comment] 2015-05-27 17:44
@yankejustin You are doing a great job here for the project, but I would add only reluctantly somebody. I hope you understand this. :)

@rabbitsmith You have a pretty scary ISP if it bans uploading of files. :o Is this restricted to all kinds of files? You should upgrade your Windows 10 to the latest preview version, maybe there's the problem.

**Comment by yankejustin** [comment] 2015-05-27 17:49
@MaxXor Yes I understand. Unfortunately adding contributors is a huge jump in power since it is a public repository.
I think we really should fix Remote Shell before we release the next version of xRAT. The input it accepts is still very lenient, such as <code> exit</code> (simple trimming of the command, then checking). It also doesn't provide error output of the client's shell yet. I almost have it working, though. :)

**Comment by MaxXor** [comment] 2015-05-27 17:51
Ok. :)

I have just added the trimming.

**Comment by MaxXor** [comment] 2015-05-29 21:43
Please do some more tests, the last commits changed a lot of things.

**Comment by d3agle** [comment] 2015-05-29 21:53
Nice changes! I'm having trouble breaking things now! :'(

**Comment by d3agle** [comment] 2015-05-31 15:34
There is a noticeably large memory leak in the server.  
To reproduce: Launch 50-100 clients.  Select all -> Send reconnect command -> watch xRAT.exe in taskmgr -> repeat sending reconnect commands when clients reconnect

**Comment by MaxXor** [comment] 2015-05-31 17:24
Updated the client & server a bit again, added some more locks & fixed the documentation. The [Server.cs](https://github.com/MaxXor/xRAT/blob/master/Server/Core/Server.cs) documentation is complete, the Client.cs 50% each.

Gonna work on this memory leak now.

**Comment by MaxXor** [comment] 2015-06-02 21:19
Does the memory leak fix work reliable for you?

**Comment by d3agle** [comment] 2015-06-02 21:39
It is working fine for me.  Memory is being reallocated, and I haven't noticed too much of a performance issue.

**Comment by yankejustin** [comment] 2015-06-02 22:00
Would you be able to provide a rough estimate of the cpu cost? It is nice to know it isn't as big of a hit as I thought. :)
Not quite sure how many times the garbage collector would try to compress the LOH...

**Comment by yankejustin** [comment] 2015-06-02 22:01
@MaxXor Also, thanks for the "green apple"! x)

**Comment by d3agle** [comment] 2015-06-02 22:24
Surprisingly, the only significant CPU usage that occurs is when the server is allocating the resources for each client.  My i7 2600k jumps from 0% idle to ~25-35% when the clients are connecting.  When I sent a command to reconnect 100 clients, my CPU usage jumped up to ~7%

**Comment by yankejustin** [comment] 2015-06-02 23:31
@d3agle I would appreciate if you would check the performance change on <b><a href="https://github.com/yankejustin/xRAT/tree/Experimental">my experimental branch</a></b> to see if what I did helps out with the CPU usage.

**Comment by MaxXor** [comment] 2015-06-08 13:50
Could anyone help me test the branch `dev-buffer`? I think I'm done improving the buffer management.

Changes: https://github.com/MaxXor/xRAT/pull/263#issuecomment-109762339

**Comment by yankejustin** [comment] 2015-06-08 15:38
@MaxXor Think we could add an <code>#if DEBUG</code> at the builder to allow the creation of multiple clients at one time for easier testing of many clients? It would certainly save some time!
Perhaps add a little TextBox for numeric input at initialization of the Builder Form in <code>DEBUG</code> mode to generate that many clients. :)
I will help you test it tonight.

**Comment by MaxXor** [comment] 2015-06-08 15:39
What I do while testing is replacing the setting `MUTEX` with `public static string MUTEX = Guid.NewGuid().ToString();`

**Comment by yankejustin** [comment] 2015-06-08 15:42
Hmmm. Perhaps I could do a bit of changes to make a new Configuration for testing multiple clients by imitating the <code>RELEASE</code> setting. Would you suppose such an addition would be beneficial?

**Comment by yankejustin** [comment] 2015-06-08 15:42
That is a nice point about the <code>MUTEX</code>. Thank you for the reminder.

**Comment by yankejustin** [comment] 2015-06-08 23:22
@d3agle @MaxXor Would you please help me test my <b><a href="https://github.com/yankejustin/xRAT/tree/NewConfiguration">new configuration</a></b> that I made for testing multiple clients please? The only part that does <b>not</b> work is the client. The client just crashes and I am not quite sure why. After starting all the clients, they just stop working.
Perhaps I set a setting for the client incorrectly...

**Comment by yankejustin** [comment] 2015-06-09 00:17
Oh wait. I take that back. The client doesn't work for me on the <code>MaxXor/dev-buffer</code> branch at all. I'm going to open an issue for it: it likely is not the fault of my code on the new configuration. We shall see...

**Comment by d3agle** [comment] 2015-06-09 00:43
@yankejustin, @MaxXor changed the namespace for the networking part of the client/server to `xCore.Client.Networking` but forgot to add it in the `Build/Renamer.cs`.

That should fix it

**Comment by d3agle** [comment] 2015-06-09 00:43
Sorry, I meant `xClient.Core.Networking`

**Comment by yankejustin** [comment] 2015-06-09 00:54
Oh, good. Thank you! :)

**Comment by yankejustin** [comment] 2015-06-09 00:56
@d3agle Would you mind sending me a pull request please? I would like to test my new configuration. :)

**Comment by yankejustin** [comment] 2015-06-09 00:57
I think it would help you out quite a great deal.

**Comment by d3agle** [comment] 2015-06-09 01:00
I'm sorry I don't understand, what would I be sending a pull request for?  I'll pull your branch and test it out. :D

**Comment by yankejustin** [comment] 2015-06-09 01:06
I did notice I forgot to exclude the <code>Label</code> for configurations other than <code>MULTI_CLIENT</code>... I will fix it in a minute. :)

**Comment by d3agle** [comment] 2015-06-09 01:21
How would I go about creating multiple clients?  I changed both Build options for Client/Server but I don't see anything where I can select how many Clients to create.

**Comment by yankejustin** [comment] 2015-06-09 01:38
If you select the "Multi-Client Release" Configuration, re-build the server and run it. You should see it on the bottom-right corner of the Builder Form.

**Comment by yankejustin** [comment] 2015-06-09 01:43
Make sure you restart Visual Studio because adding the new configuration meant I had to modify the project files.

**Comment by yankejustin** [comment] 2015-06-09 16:09
@d3agle Sorry to bug you again but I am unable to see the reason why my <code>yankejustin/NewConfiguration</code> branch still won't build functional clients... Is there any change you can see that could be the cause of this?

**Comment by d3agle** [comment] 2015-06-09 21:34
@yankejustin, No worries, I'm hardly ever bugged. :)  I can take a look tonight when I'm free.

**Comment by MaxXor** [comment] 2015-06-09 21:36
@d3agle Would you like to also test the new client & server from `dev-buffer` in Release mode? :)

**Comment by d3agle** [comment] 2015-06-09 21:40
@MaxXor, Sure thing.  I've already played with it a little bit, and everything seemed good.  Memory usage was down dramatically, as well as CPU usage.  I believe that there was one instance where only some of the clients connected out of all 100, however I'm unsure if it was a fault on my part with testing or if there is a bug somewhere.  I can look into it as well! :)

**Comment by MaxXor** [comment] 2015-06-09 21:41
@d3agle Yea, that would be great if you can find the cause for it mayb. :)

**Comment by yankejustin** [comment] 2015-06-10 01:34
@d3agle In my case, I can get <b>no</b> clients to connect correctly. Any that I try to start will crash on this configuration...
<h1>More Information</h1>
1. Operating System
    - Windows 7 Home Premium
    - Service Pack 1
2. System
    - Processor: Intel(R) Core(TM) i7 CPU    -    920 @ 2.67 GHz 2.67 GHz
    - RAM: 16 GB
    - System type: 64-bit Operating System
3. Connection
    - Local Connection to the server -(127.0.0.1)-
    - Default port -(4282)-
4. Client
    - Default Settings
    - No administrator privileges (I have tried, still doesn't work)
    - Keylogger is not enabled
<h1>Starting the Client</h1>
1. Double-Click the client
2. Nothing happens for (~15)-(~30) seconds, then a message from Windows will pop up stating that the program has stopped working.
3. As one can guess, by then the program can not recover and it will cause the client to crash.
<h1>Final Notes</h1>
1. This is likely an issue with the Settings for the client. I have tried debugging to see what is causing this issue but it will function correctly. There are no problems. When I use the <code>RELEASE</code> configuration, the clients built only crash.

**Comment by d3agle** [comment] 2015-06-10 02:45
@yankejustin, when the client crashes it should leave a metadata file in `%temp%` and it should show what exception is being thrown runtime.  Could you try to get the client to crash again?  Instead of closing the dialog that pops up, allow it to collect the information and it will display another dialog with a path to the `.dmp` file and an `.xml` file (the xml file will contain the info)

**Comment by yankejustin** [comment] 2015-06-10 04:07
@d3agle A client from earlier this morning was used, so it works to some extent. My current issue is having the client show up in the GUI using the latest dev branch. While the client does connect successfully (and is stored in <code>_clients</code>), the client is not shown in the <code>ListView</code>. I cannot also do things like show the Statistics (states that there are no connected clients). Again, they are in <code>_clients</code> and <code>ObjectDisposedExceptions</code> are thrown when I attempt to stop listening on the server for each of the clients, but they are not fully connected. I do know that the <code>ObjectDisposedException</code> is thrown when we disconnect the client and call to close the socket (<code>if (_handle != null) _handle.Close(); etc...</code>... Not sure what is preventing the client from calling <code>Process</code>... It is not getting past <a href="https://github.com/MaxXor/xRAT/blob/dev-buffer/Server/Core/Networking/Server.cs#L270">here</a> and it must for the server to update the GUI and do further processing...

**Comment by MaxXor** [comment] 2015-06-10 10:06
The `ObjectDisposedException` is normal when clients are connected and the server stops listening, because at [this line](https://github.com/MaxXor/xRAT/blob/dev-buffer/Server/Core/Networking/Client.cs#L206) it can't receive anymore from the socket. :)

Well, I've tested this now with multiple clients using the RELEASE mode and it's working fine, with enabled/disabled startup and installtion.. :disappointed: 

Please completely rebuild your solution in RELEASE mode and re-build your client and test it again.
Also try disabling your windows firewall for this.

**Comment by MaxXor** [comment] 2015-06-11 08:22
This issue should be gone now, can you confirm this with the latest commit? :)

**Comment by d3agle** [comment] 2015-06-11 20:53
@MaxXor, good work!  I apologize but I won't be able to participate for ~3 weeks.  I have a lot of work to do in school, and I need to concentrate on this work instead.  Keep up the good work guys! :+1:

**Comment by MaxXor** [comment] 2015-06-11 20:55
@d3agle Thanks. No problem! =)

**Comment by yankejustin** [comment] 2015-06-12 00:05
Yeah I have been pretty busy these last few days. I will test tonight if I can.

**Closed** 2015-06-14 19:02 UTC
Labels: help wanted
