### ISSUE TITLE
keylogger stops logging after some time

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#91] opened 2015-05-06 18:13 UTC
i setup a client and tested it
the keylogger was working great but unfortunately it suddenly stopped working after 30 min aprox. and just log the windows title and blank line under it
![xrat](https://cloud.githubusercontent.com/assets/12255107/7500143/47ad9d66-f42c-11e4-89bd-fb63b42b6f64.png)

this is an attachment shows the problem

**Comment by yankejustin** [comment] 2015-05-06 20:09
Did your keyboard disconnect? My first thought would be that the Keylogger was attempting to get the state of a keyboard that was invalid.
Was the client built with any non-default or unusual settings?

**Comment by DragonzMaster** [comment] 2015-05-06 20:52
no it's laptop's keyboard so it can't be diconnected
and its setting was the default which came with it i have just changed the host to "127.0.0.1"
and  the keylogger didn't work again until i have reopen it

**Comment by yankejustin** [comment] 2015-05-06 21:07
Run the client in debug mode and please tell me if an exception is raised in the output window.

**Comment by DragonzMaster** [comment] 2015-05-06 22:16
i tried debug mode but it seems that the client don't connect to the server correctly :/

**Comment by yankejustin** [comment] 2015-05-06 23:15
If I leave the keylogger on for 30 minutes, would I experience the same troubles?

**Comment by DragonzMaster** [comment] 2015-05-07 00:16
i don't know but that which happened with me and the Pic above shows what happened

**Comment by d3agle** [comment] 2015-05-07 00:41
Are you using the latest solution?  Do you use alt + tab to switch between applications?

**Comment by vigneshkarthisan** [comment] 2015-05-07 01:19
Do you have an external monitor setup?. MSDN says ```GetAsyncKeyState()``` method won't work if current desktop is not the primary desktop.

**Comment by DragonzMaster** [comment] 2015-05-07 01:29
yes i am using the latest solution and using ALT+Tab to switch
and i am working on only 1 monitor

**Comment by d3agle** [comment] 2015-05-07 01:38
It looks like theres a problem writing the file somewhere

**Comment by vigneshkarthisan** [comment] 2015-05-07 01:40
There wouldn't be a problem writing to file, because the window titles are logged.

**Comment by d3agle** [comment] 2015-05-07 01:44
There might be, not because of that, but when I ran a client, it never even created a new file after had running it for a few minutes

**Comment by d3agle** [comment] 2015-05-07 01:58
@DragonzMaster, are you able to recreate this problem again after it had first happened?

**Comment by vigneshkarthisan** [comment] 2015-05-07 02:02
Was the problem solved?

**Comment by yankejustin** [comment] 2015-05-07 02:31
Certainly not the external monitor. I have multiple monitors and have had no issues with this. I hooked up my laptop to another monitor (Windows 7) and it had no issues like this. Unfortunately I don't have free time now to leave it logging keys for at least 30 minutes. Maybe tomorrow!

**Comment by yankejustin** [comment] 2015-05-07 02:32
As @d3agle asked, I am curious if this showed again or if it was a one-time issue...

**Comment by d3agle** [comment] 2015-05-07 03:29
Ok, so, this problem has happened with me as well.  Ran the client on my host and let it run while I played some games etc..  I can't pinpoint exactly how long it took for the logs to stop working, but eventually it stopped logging the keys and kept logging the Window titles.  I'm going to implement your suggestion @yankejustin with the time of the logs in the window title header, from when its first created and see if I can pinpoint what might be happening

**Comment by d3agle** [comment] 2015-05-07 05:23
Here is what is happening, if someone wants to fix

http://puu.sh/hEoaF/b58c574bb9.png

**Comment by d3agle** [comment] 2015-05-07 05:24
Here is what is happening, if someone wants to fix

http://puu.sh/hEoaF/b58c574bb9.png

Object null reference, k is null

**Comment by MaxXor** [comment] 2015-05-07 09:34
Can you confirm it's fixed with the latest commit?

**Comment by d3agle** [comment] 2015-05-07 09:39
I left it running for ~2 hours and no problems

**Comment by d3agle** [comment] 2015-05-07 09:40
Prior to the null check, it would null out around 30 minutes into the client being ran.  It happened twice, around the same time, not sure why it was.

**Comment by d3agle** [comment] 2015-05-07 09:41
Now to think of it though, it was probably a dead-key.  The FromKeys method will return a null instead of a character, so that was probably why

**Comment by DragonzMaster** [comment] 2015-05-07 10:31
sorry guys i was sleeping as i see there is someone else faced this problem
and unfortunately when i run the debug release the client don't connect to the server (commit 311)
so i can't know if there is any exception thrown

**Comment by d3agle** [comment] 2015-05-07 10:33
The problem is fixed now

**Comment by DragonzMaster** [comment] 2015-05-07 11:35
i have downloaded the latest release and testing it

**Comment by yankejustin** [comment] 2015-05-07 12:37
Seems good. Unless otherwise stated by @DragonzMaster if a problem is seen again, this can probably be closed.

**Comment by DragonzMaster** [comment] 2015-05-07 13:09
no no i haven't seen the problem again since using the latest commit until now
good work guys :+1:

**Closed** 2015-05-07 16:02 UTC
Labels: bug
