### ISSUE TITLE
File Manager Disconnected

### ISSUE THREAD

**Issue by AlienHack** [MaxXor/xRAT#275] opened 2015-07-10 02:51 UTC
Hello, I have an issue when trying to download file larger than approximately 1-2 MB using the yesterday build.

When downloading file(large and small) with local machine, the file manager work just fine, but if i'm trying to download file (1MB ++ ) from remote PC, the connection was lost and disappeared then it reappeared after a while.

**Comment by AlienHack** [comment] 2015-07-10 02:54
![screenshot_5](https://cloud.githubusercontent.com/assets/8213866/8611329/9f575a26-26e9-11e5-9859-ea61cac84edd.png)

**Comment by MaxXor** [comment] 2015-07-10 09:39
Thanks, I can reproduce this and already partly fixed it. Now it seems only to disconnect when the file is over 300MB. I will push the commits soon.

**Comment by xDESTROYx** [comment] 2015-07-10 10:08
same problem.

**Comment by MaxXor** [comment] 2015-07-10 10:37
Will be fixed today. :)

**Comment by MaxXor** [comment] 2015-07-10 12:28
Can you test if the bug is fixed for files < 400MB?

**Comment by AlienHack** [comment] 2015-07-11 04:09
Okay, will test and gonna report it here

**Comment by yankejustin** [comment] 2015-07-11 14:42
@MaxXor Have you found the reason it was not initially working, or was the logic for networking just flawed in this area?

**Comment by yankejustin** [comment] 2015-07-11 14:42
I now have some free time again, and I would certainly not mind cleaning up this area before going back to the Registry Editor!

**Comment by MaxXor** [comment] 2015-07-11 14:44
@yankejustin The networking was the problem here. You can work on the registry editor, I'll do this here. :)

**Comment by yankejustin** [comment] 2015-07-11 14:46
Got it. I have a request since I have to go to work for a while: would you mind helping me fix some conflicts from all of the commits since I last was able to work on the Registry Editor and submit a PR to that branch? It would help very much. :)
Thank you!

**Comment by AlienHack** [comment] 2015-07-11 16:36
I've tried download 120 MB file, it's working fine. I think this commit resolved the problem.

**Comment by MaxXor** [comment] 2015-07-11 16:38
@AlienHack Nice to hear that it's working! Thanks.

**Closed** 2015-07-11 17:02 UTC
Labels: bug
